//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerfront.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.Messages = new HashSet<Messages>();
        }
    
        public int ConversationID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Website { get; set; }
        public string PageName { get; set; }
        public string PageURL { get; set; }
    
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
