//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerfront.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageID { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public string Message { get; set; }
        public string MessageFrom { get; set; }
        public Nullable<int> MessageUserID { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
    
        public virtual Conversation Conversation { get; set; }
    }
}
