//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerfront.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Conversation = new HashSet<Conversation>();
        }
    
        public int VisitorID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Browser { get; set; }
        public string Device { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<Conversation> Conversation { get; set; }
    }
}
